### ISSUE TITLE
No TravisCI integration

### ISSUE THREAD

**Issue by nomadeagle** [22d3e06/instalist-server#1]
Hozzáadom a .travis.yml fájlt és letesztelem, hogy működik-e jól.

Tesztelés: Elrontom az egyik unit tesztet, hogy jó működéskor faileljen, aztán revertalom a változtatást.

**Comment by nomadeagle** [comment]
Wiki oldal:
https://github.com/22d3e06/instalist-server/wiki/TravisCI

**Comment by Oviom** [comment]
Ellenőriztem a módosításokat. Reprodukáltam a tesztet másik unit-test módosításával, és frissítettem a Wiki oldalt.

**Comment by micskeiz** [comment]
OK
