### ISSUE TITLE
No SonarQube usage

### ISSUE THREAD

**Issue by hdorottya** [22d3e06/instalist-server#2]
A build.gradle manipulációjával kijátszottam a pom.xml generálását a SonarQube működéséhez, melynek hiányára az eszköz használat közben felhívta a figyelmet. Az ellenőrzés eredménye nem mutatott bug-ot, illetve sérülékenységet, viszont számos code smell-re és duplikációra hívta fel a figyelmet a projektben. Ezután ezek egy részét javítottam ki!

**Comment by hdorottya** [comment]
#[unused import removed](https://github.com/22d3e06/instalist-server/commit/d27d985b8e13659fed0588a96d531b6eb8c69567)

**Comment by hdorottya** [comment]
#[useless parenthesis removed](https://github.com/22d3e06/instalist-server/commit/162a8d4db1d1e89242a1f9dc7c4d777d25dbff09)

**Comment by hdorottya** [comment]
#[block of commented-out lines of code removed](https://github.com/22d3e06/instalist-server/commit/162a8d4db1d1e89242a1f9dc7c4d777d25dbff09)

**Comment by hdorottya** [comment]
#[useless parenthesis removed](https://github.com/22d3e06/instalist-server/commit/ec659ddc5f6798a39bf20457008f8cb83fbf4e56)

**Comment by hdorottya** [comment]
#[unused imports removed](https://github.com/22d3e06/instalist-server/commit/17199d3c97683327469348ffefa2314abf48e8d9)

**Comment by hdorottya** [comment]
#[block of commented-out lines of code removed](https://github.com/22d3e06/instalist-server/commit/09bdea22ff0dd0997211ec888a55622a1407d95e)

**Comment by hdorottya** [comment]
#[block of commented-out lines of code removed](https://github.com/22d3e06/instalist-server/commit/105c3ff88b709b43567230537a32b40ae442ebf0)

**Comment by hdorottya** [comment]
#[modify build.gradle to avoid pom.xml](https://github.com/22d3e06/instalist-server/commit/b02e9ff0483cbcbd424f0a237741d2311b07c66d)

**Comment by hdorottya** [comment]
#[block of commented-out lines of code removed](https://github.com/22d3e06/instalist-server/commit/4b6f9f10288c320c601eb176c985740b7bb863d0)

**Comment by hdorottya** [comment]
#[block of commented-out lines of code removed](https://github.com/22d3e06/instalist-server/commit/a1f5fd01dacc622def73edc7ec44afd86f65a1a7)

**Comment by hdorottya** [comment]
#[useless parenthesis removed](https://github.com/22d3e06/instalist-server/commit/af22e1db49484d6c3e90000eb731538bb4399418)

**Comment by hdorottya** [comment]
#[useless parenthesis removed](https://github.com/22d3e06/instalist-server/commit/35318067e7a47da8f8e1aa58c34d19e8cc64ac7c)

**Comment by hdorottya** [comment]
#[useless parenthesis removed](https://github.com/22d3e06/instalist-server/commit/b8bbd064defdeb44997500ada43c1e80e6c7c8e8)

**Comment by hdorottya** [comment]
#[unused imports removed](https://github.com/22d3e06/instalist-server/commit/95952cbd5fb714598e48b11abd9a16723b968c32)

**Comment by hdorottya** [comment]
#[unused imports removed](https://github.com/22d3e06/instalist-server/commit/9bfb0e42fe8b553a54da50ffafc701bb1e2553f9)

**Comment by hdorottya** [comment]
#[unused imports removed](https://github.com/22d3e06/instalist-server/commit/3da8e0a27ea0302e080e21e1781f2fbf5cacb79d)

**Comment by hdorottya** [comment]
Wiki oldal: [https://github.com/22d3e06/instalist-server/wiki/SonarQube](https://github.com/22d3e06/instalist-server/wiki/SonarQube)

**Comment by ofalvai** [comment]
Én szívesen leellenőrzöm. A beüzemelésnél volt valami extra lépés, amire figyeljek? Ha igen, beleírjuk a wikibe?

**Comment by hdorottya** [comment]
Arra figyelj, hogy a build.gradle-be bekeruljon az elejere a plugin, amit commitoltam. Ezzel kikeruljuk a pom.xml hianyat. En linuxon csinaltam, ott ennyi volt es magat az analitikat a 'gradle sonarqube' paranccsal tudtam ott inditani, mert ugye a gradle valtoztattam. Ha windowson csinalod akkor a conf mappaban a konfiguracios fajlban a path-nal meg kell adnod a jvm elerest kulonben nem fog felallni a sonarqube

**Comment by hdorottya** [comment]
Beleirhatom a wikis oldalaba ha gondoljatok ezt

**Comment by ofalvai** [comment]
Javítottam code smell-eket:
* [3da8e0a](https://github.com/22d3e06/instalist-server/commit/d3cc19ff2125294a6d26e7bc69463b775483fe1f)
* [d3cc19f](https://github.com/22d3e06/instalist-server/commit/27af9089de158e0c997a6ea8ab0789af1e4b16e4)

És frissítettem a [wiki oldalát](https://github.com/22d3e06/instalist-server/wiki/SonarQube/2002c011d3807d134f8c01782ebc88506c4bcc5c).

**Comment by micskeiz** [comment]
OK.

A javításoknál arra figyeljetek azért, hogy ha a projekt használ konzisztensen egy adott elnevezési konvenciót (pl. lokális változónál _ prefix), akkor hiába javasol a SonarQube mást, nem biztos, hogy érdemes átírni a teljes projektet. Ez az eredeti fejlesztő döntése, hogy milyen elnevezési konvenciót szeretne használni.
