### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by ofalvai** [22d3e06/instalist-server#4]
Nekem a honlapon felsorolt szolgáltatások közül a [Coveralls](https://coveralls.io) tűnik a legegyszerűbbnek és legszimpatikusabbnak, szóval megpróbálom beüzemelni erre a repóra.
Ehhez viszont a szolgáltatásnak hozzá kéne férnie a GitHub szervezetünk adataihoz, @nomadeagle jóvá tudnád hagyni? (Úgy tudom te vagy az owner)

**Comment by ofalvai** [comment]
Beüzemeltem közben a saját forkomon a Coveralls-t (lásd #5 ), elvileg ha jóvá lesz hagyva erre a projektre is a Coveralls hozzáférés, akkor itt is menni fog.

**Comment by ofalvai** [comment]
Beüzemeltem az org repo-n (tehát ezen) is, valaki más ellenőrözhetné. Elvileg ha beléptek a [Coveralls](https://coveralls.io)ra GitHub fiókkal, akkor látni kéne a szervezet repóját.

**Comment by Oviom** [comment]
Review-et megírtam, linkeket adtam a releváns információkhoz.
