### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by hdorottya** [22d3e06/instalist-server#6]
A projekt meglévő unit tesztjei mellé még kétféle unit tesztet készítettem. Egyrészt a modell osztályokra vonatkozóan nem voltak tesztek, ezért azok alapvető funkcióinak, metódusainak tesztelésére készítettem néhányat. Másrészt a controller osztályokra vonatkozó tesztek is elég hiányosak voltak, ezért azok közül is kettőnél az AuthControllerTest-et alapul véve próbáltam növelni a teszt lefedettséget.

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/7757e5901c3fbdf4e2a69b5426b46a8cff5c8f29)

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/a65124106c0eb14f1af095a55aecbdc75e973e2e)

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/95c23024f5413cc63638494a06de4ed0f0909f67)

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/a7ca62866f7829a71f163b507eb75e926bf4315d)

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/bda3d94bae9e5b82107ed813b78ffb4bea4baa39)

**Comment by hdorottya** [comment]
[added some unit tests for basic functionality](https://github.com/22d3e06/instalist-server/commit/9c741c9848635a89a7fa5574b927f68ae1084c5f)

**Comment by hdorottya** [comment]
[modify ICategoryController](https://github.com/22d3e06/instalist-server/commit/fe12d8500ab94f8797d0a5a3ebe80cf9edf6e6a3)

**Comment by hdorottya** [comment]
[modify CategoryController](https://github.com/22d3e06/instalist-server/commit/98e568e8c2259f1206083bd27db12c6780426409)

**Comment by hdorottya** [comment]
[modify IProductController](https://github.com/22d3e06/instalist-server/commit/7349f85823bea2d6e69626f4af302c151bcfd408)

**Comment by hdorottya** [comment]
[modify ProductController](https://github.com/22d3e06/instalist-server/commit/a31f2128dec3c0e5efd31dce600df845343e3ba4)

**Comment by hdorottya** [comment]
[equals method test modified](https://github.com/22d3e06/instalist-server/commit/5ae1c142272c8e5cf962f29a6901a0d5ca799352)

**Comment by hdorottya** [comment]
Wiki oldal: [https://github.com/22d3e06/instalist-server/wiki/Unit-tests](https://github.com/22d3e06/instalist-server/wiki/Unit-tests)

**Comment by nomadeagle** [comment]
Ellenőrizve és wiki oldal frissitve.
